### ISSUE TITLE
Glob multiline issue with exclusions

### ISSUE THREAD

**Issue by sbrodehl** [bxb100/action-upload#110]
Hi there,

I ran into a problem with the multiline `include' option, or with excluding paths.

To include all files in the given cwd we can use the following glob
```yaml
include: './**'
```
but excluding some folders will not work correctly, e.g. using
```yaml
include: |
  './**'
  '!./exclude'
```
This will produce the following log, using the `webdav' provider:
```
2023-...Z ##[group]Upload files to webdav start
2023-...Z ##[endgroup]
```
where the first example copies all files as expected.

Looking at the include option, a string[] is expected, suggesting the use of `|`, but I could not find an example of this.

Have you come across anything similar?
Should tests/examples be added for multiline globs?

**Comment by bxb100** [comment]
because the multi-line string is based on YAML grammar, the code treats `'` as part of a string.

It may have confused you, so I wrote a function to remove all wrapped `'`, `"`

and a demo for this https://github.com/bxb100/action-upload-test-demo

thanks

**Comment by sbrodehl** [comment]
Thank you very much for the quick reply and the detailed demo!
