### ISSUE TITLE
Add the support of client certificate

### ISSUE THREAD

**Issue by naranyinyun** [bxb100/action-upload#50]
When uploading，use thclient certificate to access the server.  
Cloudflare offen use the JavaScript Challenge to block the request from the GitHub action.

**Comment by bxb100** [comment]
Sorry for the late response

Did you mean <https://developers.cloudflare.com/waf/>? currently, the OpenDAL does not support custom `request`, so the work way is setting CF to allow GitHub Action Host IP access[^1]

[^1]: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#ip-addresses

**Comment by naranyinyun** [comment]
> Sorry for the late response
> 
> Did you mean https://developers.cloudflare.com/waf/? currently, the OpenDAL does not support custom `request`, so the work way is setting CF to allow GitHub Action Host IP access[1](#user-content-fn-1-947bb43d92759a4220c0ab18a9db8d0d)
> 
> ## Footnotes
> 1. https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#ip-addresses [↩](#user-content-fnref-1-947bb43d92759a4220c0ab18a9db8d0d)

I have created a list that includes IP addresses from the [GitHub Meta API](https://api.github.com/meta), But some IPs are not in the GitHub Meta API  
That project has been archived, so there's no need for further replies.

Thank you for your replies!
